name: "rine_vit"

platform: "onnxruntime_onnx"

max_batch_size : 16
dynamic_batching {
    max_queue_delay_microseconds: 4000
}

input [
  {
    name: "input"
    data_type: TYPE_UINT8
    dims: [ 3, 224, 224 ]
  }
]

output [
  {
    name: "probas_bin"
    data_type: TYPE_FP32
    dims: [ 2 ],
  }
]

optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP16" }}
  ]
}}
